### ISSUE TITLE
Add the Jupyter Releaser workflow

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/litegitpuller#7]
Currently the repo is configured to use the releaser. But we can also add the releaser workflows so it's easier to make the release from the repo.

- [x] Add [jupyterlite-bot](https://github.com/jupyterlite-bot) as a collaborator to the repo
- [ ] Add workflows from: https://github.com/jupyter-server/jupyter_releaser/tree/main/example-workflows
- [x] Add `ADMIN_GITHUB_TOKEN` to the repo secrets
- [x] Add `NPM_TOKEN` to the repo secrets
- [x] Publish placeholder `litegitpuller` package on PyPI: https://pypi.org/project/litegitpuller/
- [x] Set up PyPI trusted publisher

![image](https://github.com/jupyterlite/litegitpuller/assets/591645/636dd65f-1cc9-4cf2-8db5-65eb335c6af3)

**Comment by jtpio** [comment]
cc @brichet if you think the extension is ready for an initial release

**Comment by brichet** [comment]
Thanks @jtpio for setting this up.
We can go for a first release.
